# Generated by Django 5.2.6 on 2025-10-04 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_result_answers_data_result_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('questions', models.ManyToManyField(limit_choices_to={'test__test_name': 'Daily Quiz'}, to='api.question')),
            ],
            options={
                'db_table': 'daily_quizzes',
            },
        ),
        migrations.CreateModel(
            name='UserTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Світла'), ('dark', 'Темна')], default='light', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.platformuser')),
            ],
            options={
                'db_table': 'user_themes',
            },
        ),
    ]
