# Generated by Django 5.2.6 on 2025-10-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dailyquiz_usertheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyQuiz',
        ),
    ]
